spring:
  application:
    name: sentinel-demo
  cloud:
    # nacos配置
    nacos:
      discovery:
        server-addr: 10.23.33.34:8848
    #sentinel配置
    sentinel:
      transport:
        #sentinel监控平台地址，需要额外启动dashboard平台
        dashboard: 127.0.0.1:7001
        #sentinel启动的与dashboard通信的http服务端口
        port: 8719

server:
  port: 8106

management:
  endpoints:
    web:
      exposure:
        include: '*'

# feign相关配置
feign:
  #开启sentinel支持，默认为false
  sentinel:
    enabled: true


