spring:
  application:
    name: nacos-client
  cloud:
    nacos:
      discovery:
      # nacos 服务器地址
        server-addr: 10.23.33.34:8848

server:
  port: 8101
management:
  endpoints:
    web:
      exposure:
        include: '*'
